#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

# Exit if already done
exit_if_stamped $0

# Install and initialize PyBOMBS
pip install -q pybombs || die Could not install PyBOMBS through pip!

# Add public GNU Radio recipes list
pybombs recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git \
    || die Failed to install GNU Radio recipes!

# If anything should go onto the livesdr, it better be in
# gr-recipes. Don't need gr-etcetera.
#pybombs recipes add gr-etcetera git+https://github.com/gnuradio/gr-etcetera.git

# Add local recipe configuration
pybombs recipes add livesdr config/pybombs.d/recipes \
    || die Failed to install local recipes!

# Do parallel compiles
pybombs config makewidth $MAKEWIDTH || die Unable to configure makewidth

## Create a PyBOMBS prefix that goes into skel.
rm -rf /etc/skel/pybombs
pybombs prefix init /etc/skel/pybombs || die Failed to create skel prefix
rm -f /etc/skel/pybombs/.pybombs/config.yml
refresh_or_install_file \
    /etc/skel/pybombs/.pybombs/config.yml \
    "Installing PyBOMBS prefix configuration..."
# Unfortunately, the setup_env.sh file requires absolute paths.
sed -i 's/\/etc\/skel/\$HOME/g' /etc/skel/pybombs/setup_env.sh \
	|| die Failed to reconfigure skel prefix
# Also setup PyBOMBS config
refresh_or_install_file \
    /etc/skel/.pybombs/config.yml \
    "Installing PyBOMBS user configuration..."
mkdir /etc/skel/.pybombs/recipes/
# Let's share our recipes with the user
cp -r ~/.pybombs/recipes/* /etc/skel/.pybombs/recipes/

# Exit cleanly
updated_rootfs
make_stamp $0
exit 0
